// <auto-generated />
using System;
using AttendanceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305102408_addTableVerify")]
    partial class addTableVerify
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceAPI.Entities.AppUser", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_code");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_employee_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("user_is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("user_password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("user_salt");

                    b.HasKey("Code");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("AppUser", "Settings");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AttendanceLeave", b =>
                {
                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("att_leave_employee_code");

                    b.Property<int>("Day")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_leave_day");

                    b.Property<int>("Month")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_leave_month");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_leave_year");

                    b.Property<int>("Fortnight")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_leave_fortnight");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(8)
                        .HasColumnType("datetime2")
                        .HasColumnName("att_leave_date");

                    b.Property<string>("Hours")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("att_leave_hour");

                    b.Property<int?>("Minutes")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_leave_minutes");

                    b.Property<int?>("RequisitionNumber")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_leave_requisition_number");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("att_leave_type_code");

                    b.HasKey("EmployeeCode", "Day", "Month", "Year", "Fortnight");

                    b.HasIndex("TypeCode");

                    b.ToTable("AttendanceLeave", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AttendanceRecord", b =>
                {
                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("att_rec_employee_code");

                    b.Property<int>("Day")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_rec_day");

                    b.Property<int>("Month")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_rec_month");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_rec_year");

                    b.Property<int>("Fortnight")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_rec_fortnight");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("att_rec_attendance_date");

                    b.Property<Guid?>("CheckInDeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("att_rec_check_in_device_id");

                    b.Property<double?>("CheckInLatitude")
                        .HasColumnType("float")
                        .HasColumnName("att_rec_check_in_latitude");

                    b.Property<double?>("CheckInLongitude")
                        .HasColumnType("float")
                        .HasColumnName("att_rec_check_in_longitude");

                    b.Property<string>("CheckInPhoto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("att_rec_check_in_photo");

                    b.Property<string>("CheckInSource")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("att_rec_check_in_source");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("att_rec_check_in_time");

                    b.Property<Guid?>("CheckOutDeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("att_rec_check_out_device_id");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("float")
                        .HasColumnName("att_rec_check_out_latitude");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("float")
                        .HasColumnName("att_rec_check_out_longitude");

                    b.Property<string>("CheckOutPhoto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("att_rec_check_out_photo");

                    b.Property<string>("CheckOutSource")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("att_rec_check_out_source");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("att_rec_check_out_time");

                    b.Property<int?>("StandardHourCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_rec_standard_hour_code");

                    b.Property<int?>("StandardHourWeekday")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("att_rec_standard_hour_weekday");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("att_rec_status");

                    b.Property<string>("TotalHours")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("att_rec_total_hours");

                    b.HasKey("EmployeeCode", "Day", "Month", "Year", "Fortnight");

                    b.HasIndex("CheckInDeviceId");

                    b.HasIndex("CheckOutDeviceId");

                    b.HasIndex("StandardHourCode", "StandardHourWeekday");

                    b.ToTable("AttendanceRecord", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.CancelLeave", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cancel_leave_Id");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cancel_leave_employee_code");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancel_leave_approve_date");

                    b.Property<string>("ApproverEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cancel_leave_approver_employee_code");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_date");

                    b.Property<int>("LeaveId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("cancel_leave_purpose");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cancel_leave_reject_reason");

                    b.Property<DateTime?>("RejectDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancel_leave_reject_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("cancel_leave_state");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancel_leave_submission_date");

                    b.HasKey("Id", "EmployeeCode");

                    b.HasIndex("LeaveId");

                    b.ToTable("CancelLeave", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Company", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("company_code");

                    b.Property<string>("DefaultBankAccountCode")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("company_default_bank_acc_code");

                    b.Property<string>("DefaultBankCode")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("company_default_bank_code");

                    b.Property<string>("FunctionalCurrency")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("company_functional_currency");

                    b.Property<string>("GlCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("company_gl_code");

                    b.Property<bool>("IsTaxApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("company_is_tax_applicable");

                    b.Property<bool>("IsTaxExemption")
                        .HasColumnType("bit")
                        .HasColumnName("company_is_tax_exemption");

                    b.Property<string>("NTN")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("company_ntn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("company_name");

                    b.HasKey("Code");

                    b.ToTable("Company", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Configuration", b =>
                {
                    b.Property<string>("Heading")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("configuration_heading");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("configuration_title");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("configuration_value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("configuration_value_type");

                    b.HasKey("Heading", "Title");

                    b.ToTable("Configuration", "Settings");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("department_code");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("department_company_code");

                    b.Property<DateTime?>("InactiveFromDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("department_inactive_from_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("department_is_active");

                    b.Property<string>("LeadCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("department_lead_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("department_name");

                    b.HasKey("Code");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Department", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Designation", b =>
                {
                    b.Property<int>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("designation_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("designation_name");

                    b.HasKey("Code");

                    b.ToTable("Designation", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Devices", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("device_id");

                    b.Property<bool>("CanReadLogs")
                        .HasColumnType("bit")
                        .HasColumnName("device_canreadlogs");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("device_company_code");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("device_deleted_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("device_is_active");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("device_is_delete");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime2")
                        .HasColumnName("device_last_sync");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_location");

                    b.Property<int>("MachineNumber")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("device_machine_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("device_name");

                    b.Property<int>("Port")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("device_port");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("device_status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Devices", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Employee", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_cardnumber");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("employee_company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("employee_created_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("employee_department_code");

                    b.Property<int>("DesignationCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("employee_designation_code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_email");

                    b.Property<string>("FaceImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employee_face_embedding");

                    b.Property<string>("FcmToken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("employee_fcm_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("employee_is_active");

                    b.Property<bool>("IsAppUser")
                        .HasColumnType("bit")
                        .HasColumnName("employee_is_app_user");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("employee_join_date");

                    b.Property<string>("LeadCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("employee_lead_code");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("employee_leave_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_phone");

                    b.Property<int>("StandardHourCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("employee_standard_hour_code");

                    b.Property<string>("ZkUserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("employee_zk_user_id");

                    b.HasKey("Code");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("DesignationCode");

                    b.HasIndex("StandardHourCode");

                    b.ToTable("Employee", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Entity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("entity_code");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("entity_address");

                    b.Property<int?>("AllowedRadiusMeters")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("entity_allowed_radius_meters");

                    b.Property<string>("ChildCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("entity_child_code");

                    b.Property<bool>("ClientVendor")
                        .HasColumnType("bit")
                        .HasColumnName("entity_client_vendor");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("entity_country_code");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_email");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("entity_fax");

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("entity_fiscal_year");

                    b.Property<string>("GlCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("entity_gl_code");

                    b.Property<string>("IndustryCode")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("entity_industry_code");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("entity_parent_code");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_phone");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("entity_short_name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("entity_status");

                    b.Property<double?>("latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.HasKey("Code");

                    b.ToTable("Entity", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.FaceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("face_image_id");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmpFaceImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("face_image");

                    b.HasKey("Id", "EmpCode");

                    b.HasIndex("EmpCode")
                        .IsUnique();

                    b.ToTable("FaceImages", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Holiday", b =>
                {
                    b.Property<int>("Day")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("holiday_day");

                    b.Property<int>("Month")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("holiday_month");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("holiday_year");

                    b.Property<int>("Fortnight")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("holiday_fortnight");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("holiday_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("holiday_title");

                    b.Property<int>("Weekday")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("holiday_weekday");

                    b.HasKey("Day", "Month", "Year");

                    b.ToTable("Holiday", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveBalance", b =>
                {
                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("leave_balance_employee_code");

                    b.Property<int>("Period")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_balance_period");

                    b.Property<string>("LeaveType")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("leave_balance_leave_type");

                    b.Property<decimal?>("Balance")
                        .HasMaxLength(9)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("leave_balance_balance");

                    b.HasKey("EmployeeCode", "Period", "LeaveType");

                    b.ToTable("LeaveBalance", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionBalance", b =>
                {
                    b.Property<int>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_balance_id");

                    b.Property<decimal>("Balance")
                        .HasMaxLength(9)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("leave_requisition_balance");

                    b.Property<decimal>("CurrentBalance")
                        .HasMaxLength(9)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("leave_requisition_current_balance");

                    b.Property<int>("MasterId")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_balance_master_id");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("LeaveRequisitionBalance", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_detail_id");

                    b.Property<string>("AdjustmentType")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("leave_requisition_detail_adjustment_type");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("leave_requisition_detail_display_id");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_requisition_detail_from_date");

                    b.Property<string>("LeaveTypeCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("leave_requisition_detail_leave_type_code");

                    b.Property<int>("MasterId")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_detail_master_id");

                    b.Property<decimal>("NoOfDays")
                        .HasMaxLength(9)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("leave_requisition_detail_no_of_days");

                    b.Property<string>("Purpose")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("leave_requisition_detail_purpose");

                    b.Property<int>("PurposeCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_detail_purpose_code");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("leave_requisition_detail_rejection_reason");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_requisition_detail_to_date");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("LeaveRequisitionDetail", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionMaster", b =>
                {
                    b.Property<int>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_master_id");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_requisition_master_approved_date");

                    b.Property<string>("ApproverEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("leave_requisition_master_approver_employee_code");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("leave_requisition_master_display_id");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("leave_requisition_master_employee_code");

                    b.Property<int?>("PreviousHajjYear")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_requisition_master_previous_hajj_year");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_requisition_master_rejection_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("leave_requisition_master_status");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_requisition_master_submission_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("LeaveRequisitionMaster", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("leave_type_code");

                    b.Property<int?>("NoOfDays")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("leave_type_no_of_days");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("leave_type_title");

                    b.HasKey("Code");

                    b.ToTable("LeavesType", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("CheckTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("notification_check_time");

                    b.Property<string>("CheckType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("notification_check_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("notification_createdAt");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_is_read");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("notification_location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("notification_message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("notification_title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("notification_type");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notification_user_code");

                    b.HasKey("Id");

                    b.ToTable("Notification", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RefreshToken", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("refresh_token_user_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.HasKey("UserCode");

                    b.ToTable("refresh_tokens", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RegistrationImage", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_image_code");

                    b.Property<string>("AdminCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("registration_imaget_admin_code");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("registration_image_approve_date");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("registration_image_company_code");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registration_image_employee_code");

                    b.Property<string>("FaceImage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("registration_image_face_image");

                    b.Property<bool>("HistoryStatus")
                        .HasColumnType("bit")
                        .HasColumnName("registration_image_history_status");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("registration_image_rejection_date");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("registration_image_rejection_reason");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("registration_image_request_date");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("registration_image_status");

                    b.HasKey("Code");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("registration_image", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RequisitionPurposeType", b =>
                {
                    b.Property<int>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("requisition_type_id");

                    b.Property<string>("Prupose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("requisition_purpose");

                    b.HasKey("Id");

                    b.ToTable("RequisitionPurposeType", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("role_is_hidden");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_title");

                    b.HasKey("Id");

                    b.ToTable("RoleType", "General");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.StandardHour", b =>
                {
                    b.Property<int>("GroupCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("standard_hour_group_code");

                    b.Property<int>("WeekDay")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("standard_hour_week_day");

                    b.Property<string>("HalfDayHourOnLateArrival")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("standard_hour_half_day_on_late_arrival");

                    b.Property<int?>("HalfDayMinutes")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("standard_hour_half_day_min");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("standard_hour_hours");

                    b.Property<int>("Minutes")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("standard_hour_minutes");

                    b.Property<string>("TimeIn")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("standard_hour_time_in");

                    b.Property<string>("TimeOut")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("standard_hour_time_out");

                    b.Property<string>("WeekDayName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("standard_hour_week_day_name");

                    b.HasKey("GroupCode", "WeekDay");

                    b.ToTable("StandardHour", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.StandardHourGroup", b =>
                {
                    b.Property<int>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("shg_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("shg_title");

                    b.HasKey("Code");

                    b.ToTable("StandardHourGroup", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.TaskTimeLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("time_log_id");

                    b.Property<double?>("HoursWorked")
                        .HasColumnType("float")
                        .HasColumnName("time_log_hours_worked");

                    b.Property<bool>("IsExtraWork")
                        .HasColumnType("bit")
                        .HasColumnName("is_extra_work");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_log_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("time_log_notes");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_log_start_time");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_log_stop_time");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("time_log_task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskTimeLogs", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.UserRole", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_role_user_Code");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_role_role_id");

                    b.HasKey("UserCode", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_id");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_assigned_by");

                    b.Property<string>("AssignedByName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_assigned_by_name");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("task_assign_date");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_assigned_to");

                    b.Property<string>("AssignedToName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_assigned_to_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("task_deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("task_description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("task_due_date");

                    b.Property<string>("EntityCode")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("task_entity_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("task_is_active");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("task_is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("task_priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("task_status");

                    b.Property<string>("TaskPreferance")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("task_preferance");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_title");

                    b.Property<double?>("TotalHoursWorked")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("task_total_hours_worked");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("task_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityCode");

                    b.ToTable("UserTask", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.UserVerifyOPT", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_verify_id");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_verify_email");

                    b.Property<string>("OTP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_verify_otp");

                    b.HasKey("UserID");

                    b.ToTable("UserVerifyOPT", "App");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AppUser", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithOne("AppUser")
                        .HasForeignKey("AttendanceAPI.Entities.AppUser", "EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AttendanceLeave", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithMany("AttendanceLeaves")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.LeaveType", "LeaveType")
                        .WithMany("Leaves")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.AttendanceRecord", "AttendanceRecord")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeCode", "Day", "Month", "Year", "Fortnight")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Devices", "CheckInDevice")
                        .WithMany("DeviceForCheckIn")
                        .HasForeignKey("CheckInDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendanceAPI.Entities.Devices", "CheckOutDevice")
                        .WithMany("DeviceForCheckOut")
                        .HasForeignKey("CheckOutDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithMany("AttendanceRecord")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.StandardHour", "StandardHour")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StandardHourCode", "StandardHourWeekday")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CheckInDevice");

                    b.Navigation("CheckOutDevice");

                    b.Navigation("Employee");

                    b.Navigation("StandardHour");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.CancelLeave", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.LeaveRequisitionMaster", "Leave")
                        .WithMany("CancelLeaves")
                        .HasForeignKey("LeaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leave");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Department", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Devices", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Company", "OwnerCompany")
                        .WithMany("CompanyDevices")
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerCompany");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Employee", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.StandardHourGroup", "StandardHourGroup")
                        .WithMany("Employees")
                        .HasForeignKey("StandardHourCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("StandardHourGroup");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.FaceImage", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithOne("EmployeeFaceImage")
                        .HasForeignKey("AttendanceAPI.Entities.FaceImage", "EmpCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveBalance", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionBalance", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.LeaveRequisitionMaster", "LeaveRequisitionMaster")
                        .WithMany("LeaveRequisitionBalances")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveRequisitionMaster");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionDetail", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.LeaveRequisitionMaster", "LeaveRequisitionMaster")
                        .WithMany("LeaveRequisitionDetails")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveRequisitionMaster");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionMaster", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithMany("LeaveRequisitionMasters")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RefreshToken", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.AppUser", "user")
                        .WithOne("RefreshToken")
                        .HasForeignKey("AttendanceAPI.Entities.RefreshToken", "UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RegistrationImage", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Employee", "Employee")
                        .WithMany("RegistrationImage")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.StandardHour", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.StandardHourGroup", "StandardHourGroup")
                        .WithMany("EmployeeStandardHour")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StandardHourGroup");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.TaskTimeLogs", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.UserTask", "Tasks")
                        .WithMany("TaskTimeLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.UserRole", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.RoleType", "UserRolesTypes")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceAPI.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserRolesTypes");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.UserTask", b =>
                {
                    b.HasOne("AttendanceAPI.Entities.Entity", "Entity")
                        .WithMany("UserTasks")
                        .HasForeignKey("EntityCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.AttendanceRecord", b =>
                {
                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Company", b =>
                {
                    b.Navigation("CompanyDevices");

                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Devices", b =>
                {
                    b.Navigation("DeviceForCheckIn");

                    b.Navigation("DeviceForCheckOut");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Employee", b =>
                {
                    b.Navigation("AppUser")
                        .IsRequired();

                    b.Navigation("AttendanceLeaves");

                    b.Navigation("AttendanceRecord");

                    b.Navigation("EmployeeFaceImage")
                        .IsRequired();

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequisitionMasters");

                    b.Navigation("RegistrationImage");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.Entity", b =>
                {
                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveRequisitionMaster", b =>
                {
                    b.Navigation("CancelLeaves");

                    b.Navigation("LeaveRequisitionBalances");

                    b.Navigation("LeaveRequisitionDetails");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.LeaveType", b =>
                {
                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.RoleType", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.StandardHour", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.StandardHourGroup", b =>
                {
                    b.Navigation("EmployeeStandardHour");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AttendanceAPI.Entities.UserTask", b =>
                {
                    b.Navigation("TaskTimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
